### ISSUE TITLE
Implement Plugin unit tests (required for new plugins)

### ISSUE THREAD

**Issue by marceloyb** [pyhoneybot/honeybot#36]
Objective here is to guarantee that all plugins are working as they should.

For each plugin, implement a [Positive Test and a Negative Test](https://stackoverflow.com/questions/8162423/what-is-positive-test-and-negative-test-in-unit-testing).

A guideline on how the tests should be implemented should be written so next contributors write unit tests for their plugin too. 

Suggestion of framework to use: [PyUnit](https://wiki.python.org/moin/PyUnit)

**Comment by Macr0Nerd** [comment]
To add on, this could be made a lot easier if we remove the send statements from the plugins themselves and into the main loop, and instead returned the output that we wish.

**Comment by amanzholov8** [comment]
I can try to write the unit tests for all the plugins, but could you please make unit tests for one plugin so that I can refer to it as an example?

**Comment by Macr0Nerd** [comment]
So @amanzholov8 we have to figure out how we want the unit tests to be implemented. My suggestion is that in the plugin class, we currently have it sending directly from there. I've been trying to discuss this with @Abdur-rahmaanJ but lets use the weather plugin as an example. Currently, we use

`
class Plugin:
    def __init__(self):
        pass

    def run(self, incoming, methods, info, bot_info):
        try:
            msgs = info['args'][1:][0].split()

            if info['command'] == 'PRIVMSG' and msgs[0] == '.weather':
                api_url = f"https://api.openweathermap.org/data/2.5/weather?q={msgs[1]},{msgs[2]}" \
                    f"&APPID=8801bc666d30a8cc9294feaf60c01117&units=metric"
                response = requests.get(api_url)
                response_json = response.json()

                weather = f"The weather for {response_json['name']} is {response_json['weather'][0]['description']} at " \
                    f"{int(response_json['main']['temp'])} degrees celsius"
                methods['send'](info['address'], weather)
        except Exception as e:
            print('woops plugin error ', e)
`

You can see that at the end of the run function, in the try statement we call the see the method `send` getting called. I propose that instead of 

`
methods['send'](info['address'], weather)
`

we do 

`
return weather
`

and in the main runtime loop in `run_plugins` in `main.py` we go from 

`
plugin.run(self, incoming, self.methods(), self.message_info(incoming), self.bot_info())
`

to

`
methods['send'](info['address']plugin.run(self, incoming, self.methods(), self.message_info(incoming), self.bot_info()))
`

We would have to alter a few functions, but it shouldn't be anything that compromises the program or runtime loop, it's just moving the send statements out of the plugins. Then, this would also allow us to easily test the plugins because we would get the actual output and data from them.

But alas this is just my two cents.

**Comment by m-pitera** [comment]
I think that we could pull out a method from run() and test that itself. That way we would just test whether the weather function works. Using the same example:

```
class Plugin:
    def __init__(self):
        pass

    def run(self, incoming, methods, info, bot_info):
        try:
            msgs = info['args'][1:][0].split()

            if info['command'] == 'PRIVMSG' and msgs[0] == '.weather':
                weather = get_weather()
                    f"{int(response_json['main']['temp'])} degrees celsius"
                methods['send'](info['address'], weather)
        except Exception as e:
            print('woops plugin error ', e)

    def get_weather():
        api_url = f"https://api.openweathermap.org/data/2.5/weather?q={msgs[1]},{msgs[2]}" \
                    f"&APPID=8801bc666d30a8cc9294feaf60c01117&units=metric"
        
        response = requests.get(api_url)
        response_json = response.json()

        weather = f"The weather for {response_json['name']} is {response_json['weather'][0]['description']} at " \

        return weather
```

Like this we can detach the actual plugin functionality and test that. In this case we would test the `get_weather()` method.

I can write unit tests for this, i just want to confirm the execution.

**Comment by AngeloGiacco** [comment]
has any work been done on this?

**Comment by Macr0Nerd** [comment]
Not at all

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Macr0Nerd** [comment]
@AngeloGiacco I think the best course of action would be to have the run action return a state of itself so that it can be analyzed for unit testing

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by paulosgf** [comment]
Implemented Github CI/CD with Github Actions.
This contemplates:
- Flake8 linter tests.
- Bandit security tests.
- Integration Unit tests.
